name: certify_flutter_web
description: "Una aplicación web para preparación de certificación Flutter AFD-200."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  flutter_markdown: ^0.7.0
  shared_preferences: ^2.2.2
  flutter_syntax_view: ^4.0.0
  url_strategy: ^0.2.0
  http: ^1.1.2
  url_launcher: ^6.3.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/data/
